import type { Metadata } from "next";
import Link from "next/link";
import ShopifyEdit from "@/components/ShopifyEdit";
import catalog from "@/data/shopify-catalog.json";
import type { ShopifyEdit as ShopifyCatalog } from "@/lib/shopify-import";
import { absoluteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "The Extended Edit",
  description:
    "Explore eclectic streetwear, graphic tees, layers, accessories and more in Hustler Dior’s extended catalog preview.",
  alternates: { canonical: absoluteUrl("/curated") },
  robots: { index: false, follow: true },
};
export default function CuratedPage() {
  return (
    <main id="main" tabIndex={-1}>
      <section className="extended-heading">
        <Link href="/#collection">← BACK TO HD ORIGINALS</Link>
        <p className="eyebrow">MORE EXPRESSION. MORE POSSIBILITIES.</p>
        <h1>
          THE EXTENDED
          <br />
          <span>EDIT.</span>
        </h1>
        <p>
          Graphic statements. Unexpected textures. A wider world of streetwear.
        </p>
        <p className="extended-disclosure">
          Catalog preview — these pieces are not available to order yet.
        </p>
      </section>
      {/* Generated by the validated inventory:shopify import, never an order feed. */}
      <ShopifyEdit catalog={catalog as ShopifyCatalog} />
    </main>
  );
}
